version: "3.2"  
services:   


  redis:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_redis
      networks:
       - ags_network      
      ports:
       - "6379:6379"
      volumes:
       - /usr/redis_database/:/data/


  webadmin:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_nginx_webadmin
      #ports:
      # - "8080:8080"
      networks:
       - ags_network

  webjs:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_nginx_client_js
      #ports:
      # - "8080:8080"
      networks:
       - ags_network


  openresty:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_openresty_dev
      networks:
       - ags_network
#      ports:
#       - "80:80"
      volumes:
       - /root/es/code:/usr/ib


  es:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_elasticsearch
      ports:
        - "9200:9200"
      networks:
       - ags_network



networks:  
  ags_network:
    external: true

