version: "3.2"  
services:   


  redis:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_redis
      networks:
       - ags_network      
      ports:
       - "6379:6379"
      volumes:
       - /usr/redis_database/:/data/

#  proxy:
#      image: registry.cn-hangzhou.aliyuncs.com/ags/image_openresty_proxy:latest
#      networks:
#       - ags_network
#      ports:
#       - target: 80
#         published: 80
#         protocol: tcp
#         mode: host
#       - target: 433
#         published: 433
#         protocol: tcp
#         mode: host
##      deploy:
##        replicas: 1
##        placement:
##          constraints: [node.labels.env==front]
#      depends_on:
#       - webjs
#       - openresty


  webadmin:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_nginx_webadmin
      #ports:
      # - "8080:8080"
      networks:
       - ags_network
      depends_on:
       - redis
       - openresty


  openresty:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_openresty_dev
      networks:
       - ags_network
      volumes:
       - /root/es/code:/usr/ib
      depends_on:
       - redis

  es:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_elasticsearch
      ports:
        - "9200:9200"
      networks:
       - ags_network

  webjs:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_nginx_client_js
      #ports:
      # - "8080:8080"
      networks:
       - ags_network
      depends_on:
       - webadmin
       - openresty


  proxy:
      image: registry.cn-hangzhou.aliyuncs.com/ags/image_openresty_proxy
      deploy:
       mode: global
      ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      networks:
       - ags_network
      depends_on:
       - webjs
       - openresty


networks:  
  ags_network:
    external: true

